debug: true
server:
  port: 8082
dubbo:
  application:
    name: demo-service-dubbo
  registry:
    register: true
    id: zk_2181
    address: zookeeper://1.12.241.116:2181
    group: demo
  consumer:
    check: false
  scan:
    base-packages: com.ljm
  protocol:
    name: tri
    port: 29002
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  rabbitmq:
    host: 1.12.241.116
    port: 5672
    virtual-host: test
    username: admin
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1
          initial-interval: 30000ms
        default-requeue-rejected: false
        prefetch: 1

  datasource:
    url: jdbc:mysql://1.12.241.116:3306/spring-dubbo-demo?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

logging:
  config: classpath:log4j2-spring.xml
  level:
    root: trace
  file:
    path: classpath:logs
