server:
  port: 8089
debug: true
spring:
  main:
    lazy-initialization: false
  application:
    admin:
      enabled: true
  profiles:
    active: dev

dubbo:
  application:
    name: demo-service-dubbo
  registry:
    address: zookeeper://1.12.241.116:2181
    group: demo
  protocol:
    name: tri
    port: 29001
  scan:
    base-packages: com.ljm
  provider:
    timeout: 1000
  config-center:
    address: zookeeper://1.12.241.116:2181
  metadata-report:
    address: zookeeper://1.12.241.116:2181

