
server:
  port: 8089

dubbo:
  application:
    name: demo-service-dubbo
  registry:
    address: zookeeper://127.0.0.1:2181
    group: demo
  protocol:
    name: dubbo
    port: 29001
  scan:
    base-packages: com.ljm.service
  provider:
    timeout: 1000
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181

debug: true

spring:
  main:
    lazy-initialization: true

